name: s2am3d
channels:
  - nvidia/label/cuda-12.4.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cuda=12.4.0
  - cuda-cccl_linux-64=13.0.85
  - cuda-command-line-tools=13.0.2
  - cuda-compiler=12.4.0
  - cuda-crt-dev_linux-64=13.0.88
  - cuda-cudart=13.0.96
  - cuda-cudart-dev=13.0.96
  - cuda-cudart-dev_linux-64=13.0.96
  - cuda-cudart-static=13.0.96
  - cuda-cudart-static_linux-64=13.0.96
  - cuda-cudart_linux-64=13.0.96
  - cuda-culibos-static=13.0.85
  - cuda-cuobjdump=13.0.85
  - cuda-cupti=13.0.85
  - cuda-cupti-dev=13.0.85
  - cuda-cuxxfilt=13.0.85
  - cuda-demo-suite=12.4.99
  - cuda-documentation=12.4.99
  - cuda-driver-dev=13.0.96
  - cuda-driver-dev_linux-64=13.0.96
  - cuda-gdb=13.0.85
  - cuda-libraries=13.0.2
  - cuda-libraries-dev=13.0.2
  - cuda-libraries-static=13.0.2
  - cuda-nsight=13.0.85
  - cuda-nvcc=12.4.99
  - cuda-nvdisasm=13.0.85
  - cuda-nvml-dev=13.0.87
  - cuda-nvprune=13.0.85
  - cuda-nvrtc=13.0.88
  - cuda-nvrtc-dev=13.0.88
  - cuda-nvrtc-static=13.0.88
  - cuda-nvtx=13.0.85
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-sanitizer-api=13.0.85
  - cuda-toolkit=12.4.0
  - cuda-tools=13.0.2
  - cuda-version=13.0
  - cuda-visual-tools=13.0.2
  - dbus=1.16.2
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - gds-tools=1.15.1.6
  - gmp=6.3.0
  - icu=73.1
  - ld_impl_linux-64=2.44
  - libcublas=13.1.0.3
  - libcublas-dev=13.1.0.3
  - libcublas-static=13.1.0.3
  - libcufft=12.0.0.61
  - libcufft-dev=12.0.0.61
  - libcufft-static=12.0.0.61
  - libcufile=1.15.1.6
  - libcufile-dev=1.15.1.6
  - libcufile-static=1.15.1.6
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcurand-static=10.4.0.35
  - libcusolver=12.0.4.66
  - libcusolver-dev=12.0.4.66
  - libcusolver-static=12.0.4.66
  - libcusparse=12.6.3.3
  - libcusparse-dev=12.6.3.3
  - libcusparse-static=12.6.3.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libnl=3.11.0
  - libnpp=13.0.1.2
  - libnpp-dev=13.0.1.2
  - libnpp-static=13.0.1.2
  - libnsl=2.0.0
  - libnuma=2.0.19
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvfatbin-static=13.0.85
  - libnvjitlink=13.0.88
  - libnvjitlink-dev=13.0.88
  - libnvjitlink-static=13.0.88
  - libnvjpeg=13.0.1.86
  - libnvjpeg-dev=13.0.1.86
  - libnvjpeg-static=13.0.1.86
  - libopengl=1.7.0
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxkbfile=1.1.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - ncurses=6.5
  - nsight-compute=2025.3.1.4
  - nspr=4.37
  - nss=3.117
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openssl=3.0.18
  - pcre2=10.46
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - rdma-core=60.0
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wayland=1.24.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - addict==2.4.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.12.0
    - arrgh==1.0.0
    - asttokens==3.0.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - blinker==1.9.0
    - boto3==1.42.21
    - botocore==1.42.21
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - colorlog==6.10.1
    - comm==0.2.3
    - configargparse==1.7.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - dash==3.3.0
    - decorator==5.2.1
    - docstring-parser==0.17.0
    - einops==0.8.1
    - embreex==2.17.7.post7
    - exceptiongroup==1.3.1
    - executing==2.2.1
    - fastjsonschema==2.21.2
    - filelock==3.20.0
    - flask==3.1.2
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2024.12.0
    - h11==0.16.0
    - h5py==3.15.1
    - httpcore==1.0.9
    - httpx==0.28.1
    - idna==3.11
    - imageio==2.37.2
    - importlib-metadata==8.7.1
    - ipython==8.37.0
    - ipywidgets==8.1.8
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - jmespath==1.0.1
    - joblib==1.5.3
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-core==5.9.1
    - jupyterlab-widgets==3.0.16
    - kiwisolver==1.4.9
    - lazy-loader==0.4
    - libigl==2.6.1
    - lightning==2.2.0
    - lightning-utilities==0.15.2
    - loguru==0.7.3
    - lxml==6.0.2
    - manifold3d==3.3.2
    - mapbox-earcut==2.0.0
    - markdown-it-py==4.0.0
    - markupsafe==2.1.5
    - matplotlib==3.10.8
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - mesh2sdf==1.1.0
    - mpmath==1.3.0
    - msgspec==0.20.0
    - multidict==6.7.0
    - narwhals==2.14.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nodeenv==1.10.0
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.4.2.65
    - nvidia-cuda-cupti-cu12==12.4.99
    - nvidia-cuda-nvrtc-cu12==12.4.99
    - nvidia-cuda-runtime-cu12==12.4.99
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.0.44
    - nvidia-curand-cu12==10.3.5.119
    - nvidia-cusolver-cu12==11.6.0.99
    - nvidia-cusparse-cu12==12.3.0.142
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu12==12.4.99
    - omegaconf==2.3.0
    - open3d==0.19.0
    - packaging==24.2
    - pandas==2.3.3
    - parso==0.8.5
    - pexpect==4.9.0
    - pillow==12.0.0
    - platformdirs==4.5.1
    - plotly==6.5.0
    - plyfile==1.1.3
    - polyscope==2.5.0
    - pooch==1.8.2
    - potpourri3d==1.3
    - prompt-toolkit==3.0.52
    - propcache==0.4.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycollada==0.9.2
    - pygments==2.19.2
    - pymeshlab==2023.12.post3
    - pyparsing==3.3.1
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.6.0
    - pytz==2025.2
    - pyvista==0.46.4
    - pyyaml==6.0.3
    - referencing==0.37.0
    - requests==2.32.5
    - retrying==1.4.2
    - rich==14.2.0
    - rpds-py==0.30.0
    - rtree==1.4.1
    - s3transfer==0.16.0
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - scooby==0.11.0
    - shapely==2.1.2
    - simple-parsing==0.1.7
    - six==1.17.0
    - stack-data==0.6.3
    - svg-path==7.0
    - sympy==1.14.0
    - tetgen==0.7.0
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - torch==2.4.0+cu124
    - torch-scatter==2.1.2+pt24cu124
    - torchaudio==2.4.0+cu124
    - torchmetrics==1.8.2
    - torchvision==0.19.0+cu124
    - tqdm==4.67.1
    - traitlets==5.14.3
    - trimesh==4.10.1
    - triton==3.0.0
    - typing-extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.2
    - vhacdx==0.0.10
    - viser==1.0.16
    - vtk==9.5.2
    - wcwidth==0.2.14
    - websockets==15.0.1
    - werkzeug==3.1.4
    - widgetsnbextension==4.0.15
    - xxhash==3.6.0
    - yacs==0.1.8
    - yarl==1.22.0
    - yourdfpy==0.0.58
    - zipp==3.23.0
